In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a_mul = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [16]:
print(a_mul.shape)

(3, 3)


In [17]:
print(a_mul.ndim)

2


In [18]:
print(a_mul.size)

9


In [19]:
print(a_mul.dtype)

int32


In [20]:
b_mul = np.array([[1,2,3],
                  [4,"Hello",6],
                  [7,8,9]])

In [22]:
print(b_mul.dtype)

<U11


In [24]:
print(type(b_mul[0][0]))

<class 'numpy.str_'>


In [26]:
c = np.full((2,3,4),9)
c 

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [28]:
c = np.zeros((2,3,4))
c 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
c = np.ones((2,3,4))
c 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
d = np.empty((2,3,4))
d 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [43]:
x_values = np.arange(0, 1000, 5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [46]:
#step wise 0 to 1000 in 4 steps
x_values = np.linspace(0, 1000, 4)
print(x_values)

[   0.          333.33333333  666.66666667 1000.        ]


In [49]:
print(np.nan)

nan


In [ ]:
print(np.isnan(np.nan))

In [ ]:
print(np.isnan(np.sqrt(-1)))

In [53]:
print(np.sqrt(-1))

nan


C:\Users\HP\AppData\Local\Temp\ipykernel_4872\267541580.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [ ]:
print(np.inf)

In [51]:
print(np.isinf(np.array([10])/0))

[ True]


C:\Users\HP\AppData\Local\Temp\ipykernel_4872\3767606384.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


In [52]:
print(np.array([10])/0)

[inf]


C:\Users\HP\AppData\Local\Temp\ipykernel_4872\500388721.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [54]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print (l1 *3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [55]:
print (a1 *3)

[ 3  6  9 12 15]


In [57]:
print (l1 + l2)
print (a1 + a2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]


In [61]:


a1 = np.array([1,2,3])
a2 = np.array([[1],
              [2]])

print (a1 + a2)

[[2 3 4]
 [3 4 5]]


In [77]:
s = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [78]:
print(np.delete(s, 1))

[1 3 4 5 6 7 8 9]


In [80]:
print(np.delete(s, 0, 1))

[[2 3]
 [5 6]
 [8 9]]


In [84]:
q = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

In [90]:
print(q.reshape((3,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
print(q.reshape((6,2)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [92]:
print(q.reshape((12,1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [93]:
print(q.reshape((2,2,3)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [94]:
a.resize((10,2))

In [95]:
a

array([[1, 2],
       [3, 4],
       [5, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [98]:
e = a.flatten()
e[2] = 1000
print(e)
print(a)

[   1    2 1000    4    5    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[[1 2]
 [3 4]
 [5 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [99]:
e = a.ravel()
e[2] = 1000
print(e)
print(a)

[   1    2 1000    4    5    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[[   1    2]
 [1000    4]
 [   5    0]
 [   0    0]
 [   0    0]
 [   0    0]
 [   0    0]
 [   0    0]
 [   0    0]
 [   0    0]]


In [104]:
#Swapping columns and rows

In [105]:
print(a.transpose())

[[   1 1000    5    0    0    0    0    0    0    0]
 [   2    4    0    0    0    0    0    0    0    0]]


In [106]:
print(a.swapaxes(0,1))

[[   1 1000    5    0    0    0    0    0    0    0]
 [   2    4    0    0    0    0    0    0    0    0]]


In [107]:
#Joining and Merging

In [108]:
y = np.array([[1,2,3],
              [4,5,6]])

z = np.array([[7,8,9],
              [10,11,12]])

In [109]:
d = np.concatenate((y, z), axis=0)
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [110]:
d = np.concatenate((y, z), axis = 1)
d

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [111]:
a = np.stack((y, z))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [114]:
t = np.vstack((y, z))
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [113]:
a = np.hstack((y, z))
a

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [116]:
print(np.split(t, 2, axis = 0))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [122]:
print(np.split(t, 3, axis = 1))

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [125]:
print(a.min())
print(a.max())
print(a.std())
print(a.mean())
print(a.sum())
print(np.median(a))

1
12
3.452052529534663
6.5
78
6.5


In [142]:
number = np.random.randint(100)
number


25

In [143]:
number = np.random.randint(2, size=(2,3,4))
number

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [0, 1, 1, 0]],

       [[1, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 1]]])

In [164]:
num = np.random.randint(1, 100, size=(2,3,4))
num

array([[[44, 55, 15, 49],
        [67, 31, 94,  3],
        [68, 49, 58,  6]],

       [[56, 24, 71, 19],
        [57, 65, 41, 67],
        [78, 94, 93, 91]]])

In [167]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
numbers

array([[5, 3, 4, 3, 7, 5, 7, 4, 5, 6],
       [5, 4, 7, 7, 4, 3, 4, 3, 6, 6],
       [5, 2, 4, 4, 6, 5, 3, 7, 4, 7],
       [7, 5, 2, 6, 2, 4, 5, 2, 3, 4],
       [5, 5, 4, 4, 5, 6, 7, 3, 2, 3]])

In [169]:
numbers = np.random.normal(loc=170, scale=15, size=(5,10))
numbers

array([[174.64610988, 161.14571767, 149.54505316, 194.89011715,
        170.15639626, 160.87327005, 159.13891789, 159.34496085,
        174.35863497, 161.27176911],
       [192.02930037, 182.04263696, 147.67568042, 158.40783689,
        182.94767057, 151.21330146, 163.72216947, 167.35013155,
        183.94400715, 174.33465839],
       [159.64356745, 177.61782575, 187.45308338, 177.09290898,
        170.84019737, 154.58462575, 183.71319586, 173.89468436,
        175.82049102, 154.21897372],
       [171.15230176, 204.88079758, 212.04606296, 134.46833977,
        169.07735486, 201.61695583, 156.78609135, 185.70576575,
        185.02774433, 162.51173432],
       [159.26286559, 167.45750562, 176.14144285, 180.87678852,
        193.49639724, 185.42992784, 159.35580848, 146.70471458,
        159.87083833, 127.58208335]])

In [170]:
numbers = np.random.choice([10, 20, 30, 40], size=(5,10))
numbers

array([[30, 20, 40, 20, 30, 10, 20, 10, 20, 10],
       [30, 40, 30, 30, 10, 30, 20, 10, 20, 10],
       [20, 20, 20, 20, 30, 40, 20, 10, 30, 10],
       [30, 40, 20, 20, 10, 10, 40, 10, 30, 40],
       [10, 20, 30, 40, 20, 20, 30, 40, 30, 10]])

In [171]:
np.save("myarray.npy", a)

In [172]:
f = np.load("myarray.npy")

In [173]:
f

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [181]:
np.savetxt("myarray.csv", t, delimiter=",")

In [185]:
g = np.loadtxt("myarray.csv", delimiter=",")

In [186]:
g

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])